### ISSUE TITLE
Provide steps

### ISSUE THREAD

**Issue by esQmo** [FabioXimenes/flutter_movie_app#1]
Great project by the way. How to make it work? I understand one needs to provide their own API Key from TheMovieDB. But how to assign it into the project? I've noticed there is a missing class `api_key.dart` so I guess the key needs to be put in here?

**Comment by esQmo** [comment]
Never mind. Created a constant string with my api key

**Comment by FabioXimenes** [comment]
@esQmo, thank you for your interest. Yes, you are right! You need to provide the API key from TMDB in a file called apy_key.dart to run the code. I added the file and a reminder in README.

**Comment by esQmo** [comment]
I just updated the README file to help other who would face the same issue. How to add it here? @FabioXimenes

**Comment by esQmo** [comment]
Well, opened a PR
